---
title: "Data in Tables Assign"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(dplyr)
shrub_volume_data<-read.csv("shrub-volume-data.csv")
#View(shrub_volume_data)
input2<-select(shrub_volume_data,length)
input2
input3<-shrub_volume_data[,c("site", "experiment")]
input3
input4<-mutate(shrub_volume_data,area=length*width)
input4

arrange(shrub_volume_data,length)

input5<-filter(shrub_volume_data, height>5)
input5
input6<-filter(shrub_volume_data, height>4, width>2 )
input6
input7<-filter(shrub_volume_data, experiment == 1|experiment == 3)
input7
input8<-filter(shrub_volume_data,is.na(height))
shrub_volume_data[is.na(shrub_volume_data$height)==FALSE,]
input9<-mutate(shrub_volume_data,volume=length*width*height)
input9
```


```{r}
# Code Shuffle ------------------------------------------------------------
library(readr)
gainesville_precip <- read_csv("C:/Users/Owner/Downloads/gainesville-precip.csv")
#View(gainesville_precip)
ppt_data <- read.csv("https://datacarpentry.org/semester-biology/data/gainesville-precip.csv", header = FALSE)
ppt_data
#Line Plot In Base R and Add points to plot
plot(monthly_mean_ppt, type = "l", xlab = "Month", ylab = "Mean Precipitation")
# Average precipitation in each month across years
monthly_mean_ppt <- colMeans(ppt_data)
monthly_mean_ppt
```


```{r}
# Bird Banding ------------------------------------------------------------
number_of_birds <- c(28, 32, 1, 0, 10, 22, 30, 19, 145, 27, 
                     36, 25, 9, 38, 21, 12, 122, 87, 36, 3, 0, 5, 55, 62, 98, 32, 
                     900, 33, 14, 39, 56, 81, 29, 38, 1, 0, 143, 37, 98, 77, 92, 
                     83, 34, 98, 40, 45, 51, 17, 22, 37, 48, 38, 91, 73, 54, 46,
                     102, 273, 600, 10, 11)
length(number_of_birds)
number_of_birds[42]
sum(number_of_birds)
min(number_of_birds)
max(number_of_birds)
mean(number_of_birds)
tail(number_of_birds, n=1)
```


```{r}
# Portal Data Manipulation ------------------------------------------------
library(readr)
surveys <- read_csv("C:/Users/Owner/Downloads/surveys.csv")
#View(surveys)
surveys2<-select(surveys,year,month, day, species_id)
surveys2

surveys3<-mutate(surveys,weight_kg=weight/1000)
surveys4<-select(surveys3,year,species_id,weight_kg)
surveys4[is.na(surveys4$weight_kg)==FALSE,]

surveysfinal<-filter(surveys,species_id=="SH")
surveysfinal
```


```{r}
# Portal Data Manipulation Pipes ------------------------------------------
library(readr)
surveys <- read_csv("C:/Users/Owner/Downloads/surveys.csv")
#View(surveys)
surveys %>%
  select(year,month, day, species_id)

surveys %>%
  mutate(weight_kg=weight/1000) %>%
  select(year,species_id,weight_kg) %>%
  filter(weight_kg!="NA")

surveys %>%
  select(year, month, day, species_id)%>%
  filter(species_id=="SH")
```


```{r}
# Portal Data challenge ---------------------------------------------------
surveys<-read.csv(("C:/Users/Owner/Downloads/surveys.csv"))
surveys1st<-select(surveys, year,month,day,species_id,weight, hindfoot_length)
surveys1st
surveys2nd<-tolower(surveys1st,species_id)
surveys3rd<-arrange(surveys1st, desc(species_id))
surveys3rd<-arrange(surveys1st, desc(weight))
surveys4th<-filter(surveys3rd,species_id=="DM"|species_id=="DO"|species_id=="DS")
filter(surveys4th,weight != "NA" & hindfoot_length != "NA")

```

