---
title: "Data VIS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# ACACIA AND ANTS
library(ggplot2)
acacia <- read.csv("ACACIA_DREPANOLOBIUM_SURVEY.txt", sep="\t", na.strings = c("dead"))
View(acacia)
# Number 1
ggplot(data=acacia) +
  geom_point(mapping=aes(x=CIRC, y=AXIS1))+
  labs(x="Circumference",
       y= "Canopy Diameter",
       title = "      ACACIA AND ANTS")
# Number 2
ggplot(data=acacia) +
  geom_point(mapping=aes(x=CIRC, y=AXIS1))+
  scale_y_log10()+
  scale_x_log10() +
  labs(x="Circumference",
       y= "Canopy Diameter",
       title = "      ACACIA AND ANTS")
# Number 3
ggplot(data=acacia) +
  geom_point(mapping=aes(x=CIRC, y=AXIS1, color= ANT))+
  labs(x="Circumference",
       y= "Canopy Diameter",
       title = "      ACACIA AND ANTS")
# Number 4
ggplot(data=acacia) +
  geom_point(mapping=aes(x=CIRC, y=AXIS1))+
  facet_wrap(~ANT)+
  labs(x="Circumference",
       y= "Canopy Diameter",
       title = "      ACACIA AND ANTS")
# Number 5
ggplot(data=acacia, 
       mapping=aes(x=CIRC, y=AXIS1))+
  geom_point()+
  geom_smooth() +
  facet_wrap(~ANT) +
  labs(x="Circumference",
       y= "Canopy Diameter",
       title = "      ACACIA AND ANTS")

```


```{r}
#2 MASS VS METABOLISM
library(ggplot2)
size_mr_data <- data.frame(
  body_mass = c(32000, 37800, 347000, 4200, 196500, 100000,
                4290, 32000, 65000, 69125, 9600, 133300, 150000, 407000,
                115000, 67000,325000, 21500, 58588, 65320, 85000, 135000,
                20500, 1613, 1618),
  metabolic_rate = c(49.984, 51.981, 306.770, 10.075, 230.073, 
                     148.949, 11.966, 46.414, 123.287, 106.663, 20.619, 180.150, 
                     200.830, 224.779, 148.940, 112.430, 286.847, 46.347,
                     142.863, 106.670, 119.660, 104.150, 33.165, 4.900, 4.865),
  family = c("Antilocapridae", "Antilocapridae", "Bovidae",
             "Bovidae", "Bovidae", "Bovidae", "Bovidae", "Bovidae",
             "Bovidae", "Bovidae", "Bovidae", "Bovidae", "Bovidae",
             "Camelidae", "Camelidae", "Canidae", "Cervidae",
             "Cervidae", "Cervidae", "Cervidae", "Cervidae", "Suidae",
             "Tayassuidae", "Tragulidae", "Tragulidae"))
ggplot(data=size_mr_data)+
  geom_point(mapping=aes(x=body_mass, y=metabolic_rate))
#2
ggplot(data=size_mr_data, mapping= aes(x=body_mass, y= metabolic_rate))+
  geom_point(size=3)+
  scale_y_log10()+
  scale_x_log10()
#3
ggplot(data=size_mr_data, mapping= aes(x=body_mass, y= metabolic_rate, color= family))+
  geom_point(size=3)+
  scale_y_log10()+
  scale_x_log10()
#4
ggplot(data=size_mr_data, mapping= aes(x=body_mass, y= metabolic_rate))+
  geom_point(size=3)+
  facet_wrap(~family)+
  scale_y_log10()+
  scale_x_log10()
```


```{r}
#3 ACACIA AND ANTS HISTOGRAM
library(ggplot2)
acacia <- read.csv("ACACIA_DREPANOLOBIUM_SURVEY.txt", sep="\t", na.strings = c("dead"))
ggplot(data=acacia,
       mapping=aes(x=ANT))+
  geom_bar()
#2
acacia <- read.csv("ACACIA_DREPANOLOBIUM_SURVEY.txt", sep="\t", na.strings = c("dead"))
ggplot(data=acacia,
       mapping=aes(x=HEIGHT))+
  geom_histogram()+
  labs(x="Height",
       y="Number of Acacia")
#3
acacia <- read.csv("ACACIA_DREPANOLOBIUM_SURVEY.txt", sep="\t", na.strings = c("dead"))
ggplot(acacia,aes(x=AXIS1))+
  geom_histogram(fill="red",position="identity",bins=30)
ggplot(acacia,aes(x=AXIS2))+
  geom_histogram(fill="black",alpha=0.5,position="identity",bins=30)+
labs(x="canopy Diameter",
     y= "Number of Acacia")
#4
acacia <- read.csv("ACACIA_DREPANOLOBIUM_SURVEY.txt", sep="\t", na.strings = c("dead"))
ggplot(acacia,aes(x=AXIS1))+
  geom_histogram(fill="red",position="identity",bins=30)
ggplot(acacia,aes(x=AXIS2))+
  geom_histogram(fill="black",alpha=0.5,position="identity",bins=30)+
  labs(x="canopy Diameter",
       y= "Number of Acacia")+
  facet_wrap(~TREATMENT)
```


```{r}
#4  ACACIA AND ANTS DATA AMNIPULATION
library(dplyr)
library(ggplot2)
trees <- read_tsv("TREE_SURVEYS.txt")
#trees<- read.delim("C:/Users/Owner/OneDrive - Fisk University/Bioinformatics/TREE_SURVEYS.txt")
trees
a1<-select(trees,SURVEY,YEAR,SITE, AXIS_1,AXIS_2)
a1
a2<-filter(a1,AXIS_1!="NA" && AXIS_2!="NA")
a3<-mutate(a2,canopy_area=AXIS_1*suppressWarnings(as.numeric(AXIS_2)))
a4<-select(a3, SURVEY,YEAR,SITE, canopy_area)
a4

twice<-inner_join(trees,a4)
twice

#2
ggplot(data=twice,
       mapping=aes(x=canopy_area, y= HEIGHT, color= TREATMENT))+
  geom_point(size=2)+
  labs(x="Canopy Area (m)",
       y= "Height (m)")+
  facet_wrap(~SPECIES)

#3
b1<-filter(twice, AXIS_1<20, AXIS_2<20)
b1
ggplot(data=b1,
       mapping=aes(x=canopy_area, y= HEIGHT, color= TREATMENT))+
  geom_point(size=2)+
  labs(x="Canopy Area (m)",
       y= "Height (m)")+
  facet_wrap(~SPECIES)
#4
by_SPECIES <- group_by(b1,SPECIES, YEAR)
nabundance<- summarize(by_SPECIES, count= table(SPECIES,YEAR))
nabundance
#5
ggplot(data=nabundance,
       mapping=aes(x=YEAR, y= nabundance))+
  geom_point()+
  geom_line()+
  facet_wrap(~nabundance, scales="free_y")
```

