---
title: "Grouping and Joining Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
# Shrub Volume Aggregation 
library(dplyr)
#1
shrub_dims <- read.csv('shrub-volume-data.csv')
by_experiment <- group_by(shrub_dims, experiment)
avg_height <- summarize(by_experiment, avg_height = mean(height))
avg_height
#2
by_site <- group_by(shrub_dims, site)
avg_height <- summarize(by_site, avg_height = max(height))
avg_height
```


```{r setup, include=FALSE}
# Shrub Volume Join
library(dplyr)
#1
shrub_dims <- read.csv('shrub-volume-data.csv')
shrub_dims2 <- read.csv("shrub-volume-experiments.csv")
shrub_dims3 <- read.csv("shrub-volume-sites.csv")
shrub_combine1 <- inner_join(shrub_dims,shrub_dims2)
shrub_combine1
#2
shrub_combinefinal <- inner_join(shrub_combine1,shrub_dims3)
shrub_combinefinal
```


```{r setup, include=FALSE}
#Portal Data Aggregation
library(dplyr)
#1
survey1<- read.csv('surveys.csv')
by_species <- group_by(survey1, species_id)
freqspecies_id <- summarize(by_species, freqspecies_id = table(species_id))
freqspecies_id
#2
by_year <- group_by(survey1, species_id, year)
nyears <- summarize(by_year, count = table(species_id, year))
nyears

#3
by_myears <- group_by(survey1, year)
xax <- summarize(by_myears, avg_mass = mean(weight, na.rm = TRUE))
filter(xax,!is.na(avg_mass))
```


```{r setup, include=FALSE}
#Fix the Code
shrub_data<-read.csv("shrub-volume-data.csv")
shrub_data %>%
  mutate(volume = length * width * height) %>%
  group_by(site) %>%
  summarize(mean_volume = mean(volume))
shrub_data %>%
  mutate(volume = length * width * height)%>%
  group_by(experiment) %>%
  summarize(mean_volume = mean(volume))
#2
#The Imported excel data is assigned to a certain variable (shrub_data)
#Since the question targets the average, ,the mean function is used instead of the max()
# The implementation of the %>% is needed to compile the code into the data set (shrub_data).
# In general, The modified code is used to sperately find the respective average of each site and experiment's volume.
```


```{r setup, include=FALSE}
#Portal Data Join
library(dplyr)
surveys<- read.csv("surveys.csv")
species<- read.csv("species.csv")
plots<- read.csv("plots.csv")
twice<-inner_join(surveys, species)
twice
#2
inner_join(plots,twice)

#3
thirdpart<- inner_join(surveys, plots)
final<- filter(thirdpart, plot_type == "Control")
final

```


```{r setup, include=FALSE}
#Portal Data dplyr review
library(dplyr)
surveys<- read.csv("surveys.csv")
species<- read.csv("species.csv")
plots<- read.csv("plots.csv")
twice<-inner_join(surveys, species)
twice

ga<- inner_join(twice,plots)
gb <- filter(ga, weight != "NA")
gc <- filter(gb, plot_type == "Control" | plot_type== "Long-term Krat Exclosure" & taxa == "Rodent")
aa <- select(gc, year, genus, species, weight, plot_type)
aa
```


```{r setup, include=FALSE}
#Extracting vectors from dataframes
library(dplyr)
surveys<- read.csv("surveys.csv")
species<- read.csv("species.csv")
plots<- read.csv("plots.csv")
#1
surveys$weight
#2
surveys[,"month"]
#3
aa<-surveys$hindfoot_length
bb<-mean(aa, na.rm=TRUE)
bb
```


```{r setup, include=FALSE}
# Building data frames from vectors
length <- c(2.2, 2.1, 2.7, 3.0, 3.1, 2.5, 1.9, 1.1, 3.5, 2.9)
width <- c(1.3, 2.2, 1.5, 4.5, 3.1, NA, 1.8, 0.5, 2.0, 2.7)
height <- c(9.6, 7.6, 2.2, 1.5, 4.0, 3.0, 4.5, 2.3, 7.5, 3.2)
genus <-c("taxus","taxus","taxus","taxus","taxus","taxus","taxus","taxus","taxus","taxus")
species <-c("baccata","baccata","baccata","baccata","baccata","baccata","baccata","baccata","baccata","baccata")
arr1<- data.frame(genus, species, length, width, height)
arr1